server:
  port: 3001
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 10
  client:
    shouldFetchRegistry: false,
    shouldRegisterWithEureka: true
    service-url:
      defaultZone: http://localhost:9010/eureka/
spring:
  application:
    name: user-service

feign:
  hystrix:
    enabled: true

#Ribbon 超时时间设置
ribbon:
  ConnectTimeout: 500
  ReadTimeout:  3000